require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/contacts_industries', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ContactsIndustry. As you add validations to ContactsIndustry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ContactsIndustry.create! valid_attributes
      get contacts_industries_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      contacts_industry = ContactsIndustry.create! valid_attributes
      get contacts_industry_url(contacts_industry)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_contacts_industry_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      contacts_industry = ContactsIndustry.create! valid_attributes
      get edit_contacts_industry_url(contacts_industry)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ContactsIndustry' do
        expect do
          post contacts_industries_url, params: { contacts_industry: valid_attributes }
        end.to change(ContactsIndustry, :count).by(1)
      end

      it 'redirects to the created contacts_industry' do
        post contacts_industries_url, params: { contacts_industry: valid_attributes }
        expect(response).to redirect_to(contacts_industry_url(ContactsIndustry.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ContactsIndustry' do
        expect do
          post contacts_industries_url, params: { contacts_industry: invalid_attributes }
        end.to change(ContactsIndustry, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post contacts_industries_url, params: { contacts_industry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested contacts_industry' do
        contacts_industry = ContactsIndustry.create! valid_attributes
        patch contacts_industry_url(contacts_industry), params: { contacts_industry: new_attributes }
        contacts_industry.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the contacts_industry' do
        contacts_industry = ContactsIndustry.create! valid_attributes
        patch contacts_industry_url(contacts_industry), params: { contacts_industry: new_attributes }
        contacts_industry.reload
        expect(response).to redirect_to(contacts_industry_url(contacts_industry))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        contacts_industry = ContactsIndustry.create! valid_attributes
        patch contacts_industry_url(contacts_industry), params: { contacts_industry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested contacts_industry' do
      contacts_industry = ContactsIndustry.create! valid_attributes
      expect do
        delete contacts_industry_url(contacts_industry)
      end.to change(ContactsIndustry, :count).by(-1)
    end

    it 'redirects to the contacts_industries list' do
      contacts_industry = ContactsIndustry.create! valid_attributes
      delete contacts_industry_url(contacts_industry)
      expect(response).to redirect_to(contacts_industries_url)
    end
  end
end
